
output$adaptorComp <- renderUI({
  if (input$adaptors == "From the list") {
    selectInput("ill_adaptors", NULL, c("Illumina TruSeq Universal",
                                        "Illumina TruSeq Index 1",
                                        "Illumina TruSeq Index 2",
                                        "Illumina TruSeq Index 3",
                                        "Illumina TruSeq Index 4",
                                        "Illumina TruSeq Index 5",
                                        "Illumina TruSeq Index 6",
                                        "Illumina TruSeq Index 7",
                                        "Illumina TruSeq Index 8",
                                        "Illumina TruSeq Index 9",
                                        "Illumina TruSeq Index 10",
                                        "Illumina TruSeq Index 11",
                                        "Illumina TruSeq Index 12",
                                        "Illumina TruSeq Index 13",
                                        "Illumina TruSeq Index 14",
                                        "Illumina TruSeq Index 15",
                                        "Illumina TruSeq Index 16",
                                        "Illumina TruSeq Index 17",
                                        "Illumina TruSeq Index 18",
                                        "Illumina TruSeq Index 19",
                                        "Illumina TruSeq Index 20",
                                        "Illumina TruSeq Index 21",
                                        "Illumina TruSeq Index 22",
                                        "Illumina TruSeq Index 23",
                                        "Illumina TruSeq Index 24",
                                        "Illumina TruSeq Index 25",
                                        "Illumina TruSeq Index 26",
                                        "Illumina TruSeq Index 27",
                                        "Illumina TruSight RNA Pan-Cancer Universal",
                                        "Illumina TruSight RNA Pan-Cancer Index 1",
                                        "Illumina TruSight RNA Pan-Cancer Index 2",
                                        "Illumina TruSight RNA Pan-Cancer Index 3",
                                        "Illumina TruSight RNA Pan-Cancer Index 4",
                                        "Illumina TruSight RNA Pan-Cancer Index 5",
                                        "Illumina TruSight RNA Pan-Cancer Index 6",
                                        "Illumina TruSight RNA Pan-Cancer Index 7",
                                        "Illumina TruSight RNA Pan-Cancer Index 8",
                                        "Illumina TruSight RNA Pan-Cancer Index 9",
                                        "Illumina TruSight RNA Pan-Cancer Index 10",
                                        "Illumina TruSight RNA Pan-Cancer Index 11",
                                        "Illumina TruSight RNA Pan-Cancer Index 12",
                                        "Illumina TruSight RNA Pan-Cancer Index 13",
                                        "Illumina TruSight RNA Pan-Cancer Index 14",
                                        "Illumina TruSight RNA Pan-Cancer Index 15",
                                        "Illumina TruSight RNA Pan-Cancer Index 16",
                                        "Illumina TruSight RNA Pan-Cancer Index 17",
                                        "Illumina TruSight RNA Pan-Cancer Index 18",
                                        "Illumina TruSight RNA Pan-Cancer Index 19",
                                        "Illumina TruSight RNA Pan-Cancer Index 20",
                                        "Illumina TruSight RNA Pan-Cancer Index 21",
                                        "Illumina TruSight RNA Pan-Cancer Index 22",
                                        "Illumina TruSight RNA Pan-Cancer Index 23",
                                        "Illumina TruSight RNA Pan-Cancer Index 24",
                                        "Illumina TruSight RNA Pan-Cancer Index 25",
                                        "Illumina TruSight RNA Pan-Cancer Index 26",
                                        "Illumina TruSight RNA Pan-Cancer Index 27",
                                        "Illumina TruSeq Single Indexes Universal",
                                        "Illumina TruSeq Single Indexes 1",
                                        "Illumina TruSeq Single Indexes 2",
                                        "Illumina TruSeq Single Indexes 3",
                                        "Illumina TruSeq Single Indexes 4",
                                        "Illumina TruSeq Single Indexes 5",
                                        "Illumina TruSeq Single Indexes 6",
                                        "Illumina TruSeq Single Indexes 7",
                                        "Illumina TruSeq Single Indexes 8",
                                        "Illumina TruSeq Single Indexes 9",
                                        "Illumina TruSeq Single Indexes 10",
                                        "Illumina TruSeq Single Indexes 11",
                                        "Illumina TruSeq Single Indexes 12",
                                        "Illumina TruSeq Single Indexes 13",
                                        "Illumina TruSeq Single Indexes 14",
                                        "Illumina TruSeq Single Indexes 15",
                                        "Illumina TruSeq Single Indexes 16",
                                        "Illumina TruSeq Single Indexes 17",
                                        "Illumina TruSeq Single Indexes 18",
                                        "Illumina TruSeq Single Indexes 19",
                                        "Illumina TruSeq Single Indexes 20",
                                        "Illumina TruSeq Single Indexes 21",
                                        "Illumina TruSeq Single Indexes 22",
                                        "Illumina TruSeq Single Indexes 23",
                                        "Illumina TruSeq Single Indexes 24",
                                        "Illumina TruSeq Single Indexes 25",
                                        "Illumina TruSeq Single Indexes 26",
                                        "Illumina TruSeq Single Indexes 27"))
  } else if(input$adaptors == "Custom Adaptor") {
    textAreaInput("adaptor", NULL, placeholder = "Add Adaptor...", height = 80)
  }
})