// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clusterTSS
NumericVector clusterTSS(DataFrame df, DataFrame clusters);
RcppExport SEXP _TSSextractR_clusterTSS(SEXP dfSEXP, SEXP clustersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type clusters(clustersSEXP);
    rcpp_result_gen = Rcpp::wrap(clusterTSS(df, clusters));
    return rcpp_result_gen;
END_RCPP
}
// firstBase
List firstBase(DataFrame df);
RcppExport SEXP _TSSextractR_firstBase(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(firstBase(df));
    return rcpp_result_gen;
END_RCPP
}
// firstSTrand
NumericVector firstSTrand(DataFrame df);
RcppExport SEXP _TSSextractR_firstSTrand(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(firstSTrand(df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TSSextractR_clusterTSS", (DL_FUNC) &_TSSextractR_clusterTSS, 2},
    {"_TSSextractR_firstBase", (DL_FUNC) &_TSSextractR_firstBase, 1},
    {"_TSSextractR_firstSTrand", (DL_FUNC) &_TSSextractR_firstSTrand, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_TSSextractR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
