# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clusterTSS <- function(df, clusters) {
    .Call('_TSSextractR_clusterTSS', PACKAGE = 'TSSextractR', df, clusters)
}

firstBase <- function(df) {
    .Call('_TSSextractR_firstBase', PACKAGE = 'TSSextractR', df)
}

firstSTrand <- function(df) {
    .Call('_TSSextractR_firstSTrand', PACKAGE = 'TSSextractR', df)
}

